/**
 * HSK Learner Tracker — Phase 4
 * Collects learning events from vocabulary.html, stores in localStorage,
 * exports as JSON for ML training data.
 *
 * INPUT:  DOM events from vocabulary.html (checkbox clicks, search input, row
 *         hover, hanzi writer clicks); localStorage key hsk_learner_events for
 *         persisted state; WORD_ID_MAP and TOPIC_WORDS embedded below.
 * ACTION: Intercepts user interactions via event listeners, maps Chinese strings
 *         to stable word IDs, accumulates timestamped event objects in memory,
 *         flushes to localStorage on a 2-second debounce, and tracks streaks /
 *         session counts. Injects a floating stats panel into document.body.
 * OUTPUT: window.LearnerTracker public API (see below); localStorage key
 *         hsk_learner_events (JSON); downloadable JSON file via exportData().
 *
 * Embedded data: WORD_ID_MAP (5357 words), TOPIC_WORDS (40 topics)
 * Generated by: scripts/generate_tracker.py
 *
 * Public API  (window.LearnerTracker):
 *   .logEvent(wordId, eventType)     — log a named event for a word
 *   .track(eventObj)                 — log a raw event object
 *   .getWordState(wordId)            — full state for one word
 *   .getTopicProgress(topicId|arr)   — progress for a topic or word ID array
 *   .getOverallProgress()            — global stats + streak
 *   .exportData()                    — download events as JSON file
 *   .getStats()                      — alias for getOverallProgress()
 *   .clear()                         — erase all data (with confirmation)
 *   .flush()                         — force immediate localStorage write
 */
(function () {
  'use strict';

  /* -- WORD ID MAP + TOPIC WORDS - loaded from data/tracker-data.json ----------
     Populated asynchronously by loadTrackerData() on DOMContentLoaded.
     Event listeners and resolveWordId() are safe before load -- they return
     null / empty results until the fetch completes. */
  var WORD_ID_MAP = {};   // keyed by chinese string -> word_id
  var TOPIC_WORDS = {};   // keyed by topic_id -> [word_ids]
  var TOTAL_WORDS = 5364; // default; overwritten after data loads

  /* ── CONSTANTS ──────────────────────────────────────────────────────────────── */
  var STORAGE_KEY  = 'hsk_learner_events';   // renamed from hsk_tracker_v1
  var OLD_KEY      = 'hsk_tracker_v1';        // migration source key
  var MAX_EVENTS   = 10000;
  var FLUSH_DELAY  = 2000;
  var MIN_HOVER_MS = 400;
  var MAX_HOVER_MS = 90000;

  /* ── MIGRATION — copy old key → new key, delete old ────────────────────────── */
  (function migrate() {
    try {
      var oldRaw = localStorage.getItem(OLD_KEY);
      if (oldRaw && !localStorage.getItem(STORAGE_KEY)) {
        localStorage.setItem(STORAGE_KEY, oldRaw);
        localStorage.removeItem(OLD_KEY);
        console.log('LearnerTracker: migrated data from ' + OLD_KEY + ' to ' + STORAGE_KEY);
      }
    } catch (e) {}
  })();

  /* ── UUID ──────────────────────────────────────────────────────────────────── */
  function uuid4() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
      var r = Math.random() * 16 | 0;
      return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });
  }

  /* ── STATE ─────────────────────────────────────────────────────────────────── */
  function blankState() {
    return {
      learner_id:    uuid4(),
      created:       new Date().toISOString(),
      session_count: 0,
      events:        []
    };
  }

  function loadState() {
    try {
      var raw = localStorage.getItem(STORAGE_KEY);
      return raw ? JSON.parse(raw) : blankState();
    } catch (e) {
      return blankState();
    }
  }

  var state      = loadState();
  var pending    = [];
  var flushTimer = null;
  var SESSION_ID    = uuid4().slice(0, 8);
  var SESSION_START = Date.now();

  /* ── FLUSH ─────────────────────────────────────────────────────────────────── */
  function scheduleFlush() {
    if (!flushTimer) flushTimer = setTimeout(flush, FLUSH_DELAY);
  }

  function flush() {
    flushTimer = null;
    if (!pending.length) return;
    state.events = state.events.concat(pending);
    pending = [];
    if (state.events.length > MAX_EVENTS) {
      state.events = state.events.slice(-MAX_EVENTS);
    }
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch (e) {
      state.events = state.events.slice(-2000);
      try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch (e2) {}
    }
  }

  /* ── WORD ID RESOLUTION ────────────────────────────────────────────────────── */
  function resolveWordId(chineseStr) {
    return WORD_ID_MAP[chineseStr] || null;
  }

  /* ── TRACK ─────────────────────────────────────────────────────────────────── */
  function track(evt) {
    evt.timestamp      = Date.now();
    evt.session = SESSION_ID;
    // Enrich with word_id if word (chinese string) is present but word_id is not
    if (evt.word && !evt.word_id) {
      evt.word_id = resolveWordId(evt.word);
    }
    pending.push(evt);
    scheduleFlush();
  }

  /* ── HELPERS ───────────────────────────────────────────────────────────────── */
  function wordFromRow(tr) {
    var el = tr ? tr.querySelector('.zh') : null;
    return el ? el.textContent.trim() : '';
  }
  function hskFromRow(tr) {
    var v = tr ? tr.getAttribute('data-hsk') : null;
    return v ? parseInt(v, 10) : null;
  }
  function isSectionRow(tr) {
    var tb = tr ? tr.parentElement : null;
    return tb && tb.id && tb.id !== 'learned-tbody' && tb.id !== 'fam-tbody';
  }

  /* ── HOOK: CHECKBOX (word_checked) ─────────────────────────────────────────── */
  document.body.addEventListener('change', function (e) {
    var cb = e.target;
    var isLearn = cb.classList.contains('learn-cb');
    var isFam   = cb.classList.contains('fam-cb');
    if (!isLearn && !isFam) return;
    var tr = cb.closest('tr');
    if (!tr) return;
    var w = wordFromRow(tr);
    track({
      event:         'word_checked',
      word:          w,
      word_id:       resolveWordId(w),
      hsk_level:     hskFromRow(tr),
      checkbox_type: isLearn ? 'learned' : 'familiar',
      checked:       cb.checked
    });
  });

  /* ── HOOK: SEARCH (search_query) ───────────────────────────────────────────── */
  var searchInput = document.getElementById('search-input');
  if (searchInput) {
    var searchTimer = null;
    searchInput.addEventListener('input', function () {
      clearTimeout(searchTimer);
      var q = this.value.trim();
      if (!q) return;
      searchTimer = setTimeout(function () {
        var visible = document.querySelectorAll(
          'tbody[id]:not(#learned-tbody):not(#fam-tbody) tr:not(.sr-hide)'
        ).length;
        track({ event: 'search_query', query: q, results_visible: visible });
      }, 600);
    });
  }

  /* ── HOOK: ROW HOVER (word_hover) ──────────────────────────────────────────── */
  var hoverMap = {};

  document.body.addEventListener('mouseover', function (e) {
    var tr = e.target.closest('tr');
    if (!tr || !isSectionRow(tr)) return;
    var w = wordFromRow(tr);
    if (!w || hoverMap[w]) return;
    hoverMap[w] = Date.now();
  });

  document.body.addEventListener('mouseout', function (e) {
    var tr = e.target.closest('tr');
    if (!tr || !isSectionRow(tr)) return;
    var w = wordFromRow(tr);
    if (!w || !hoverMap[w]) return;
    var dur = Date.now() - hoverMap[w];
    delete hoverMap[w];
    if (dur < MIN_HOVER_MS || dur > MAX_HOVER_MS) return;
    track({
      event:       'word_hover',
      word:        w,
      word_id:     resolveWordId(w),
      hsk_level:   hskFromRow(tr),
      duration_ms: dur
    });
  });

  /* ── HOOK: HANZI WRITER (stroke_play) ─────────────────────────────────────── */
  document.body.addEventListener('click', function (e) {
    var btn = e.target.closest('.hz-anim-btn, [data-hz], .stroke-btn');
    if (!btn) return;
    var tr = btn.closest('tr');
    if (!tr) return;
    var w = wordFromRow(tr);
    track({
      event:     'stroke_play',
      word:      w,
      word_id:   resolveWordId(w),
      hsk_level: hskFromRow(tr)
    });
  });

  /* ── SESSION EVENTS ────────────────────────────────────────────────────────── */
  state.session_count = (state.session_count || 0) + 1;
  track({
    event:    'session_start',
    page:     window.location.pathname.split('/').pop() || 'vocabulary.html',
    referrer: document.referrer ? document.referrer.split('/').pop() : ''
  });

  window.addEventListener('beforeunload', function () {
    var learnedCount = document.querySelectorAll('.learn-cb:checked').length;
    var famCount     = document.querySelectorAll('.fam-cb:checked').length;
    track({
      event:          'session_end',
      duration_ms:    Date.now() - SESSION_START,
      learned_count:  learnedCount,
      familiar_count: famCount
    });
    flush();
  });

  /* ── WORD STATE ────────────────────────────────────────────────────────────── */
  function eventsForWord(wordId) {
    return state.events.filter(function (e) {
      return e.word_id === wordId || (e.word && resolveWordId(e.word) === wordId);
    });
  }

  function getWordState(wordId) {
    var evts     = eventsForWord(wordId);
    var hovers   = evts.filter(function (e) { return e.event === 'word_hover'; });
    var checks   = evts.filter(function (e) { return e.event === 'word_checked'; });
    var searches = state.events.filter(function (e) {
      return e.event === 'search_query' && e.query;
    });
    var word = evts.length ? (evts[0].word || '') : '';

    // Determine current learned/familiar state from most recent check events
    var learnChecks = checks.filter(function (e) { return e.checkbox_type === 'learned'; });
    var famChecks   = checks.filter(function (e) { return e.checkbox_type === 'familiar'; });
    var isLearned   = learnChecks.length && learnChecks[learnChecks.length - 1].checked;
    var isFamiliar  = famChecks.length   && famChecks[famChecks.length - 1].checked;

    // Count searches that included this word's chinese string
    var timesSearched = word ? searches.filter(function (e) {
      return word.indexOf(e.query) !== -1 || e.query.indexOf(word) !== -1;
    }).length : 0;

    return {
      word_id:        wordId,
      word:           word,
      current_state:  isLearned ? 'learned' : isFamiliar ? 'familiar' : 'unseen',
      times_hovered:  hovers.length,
      times_checked:  checks.length,
      times_searched: timesSearched,
      hover_total_ms: hovers.reduce(function (s, e) { return s + (e.duration_ms || 0); }, 0),
      first_seen:     evts.length ? new Date(evts[0].timestamp).toISOString() : null,
      last_seen:      evts.length ? new Date(evts[evts.length - 1].timestamp).toISOString() : null
    };
  }

  /* ── TOPIC PROGRESS ────────────────────────────────────────────────────────── */
  function getTopicProgress(topicIdOrArray) {
    var wordIds, topicId;
    if (typeof topicIdOrArray === 'string') {
      topicId = topicIdOrArray;
      wordIds = TOPIC_WORDS[topicId] || [];
    } else if (Array.isArray(topicIdOrArray)) {
      topicId = null;
      wordIds = topicIdOrArray;
    } else {
      return null;
    }

    var learned = 0, familiar = 0, unseen = 0;
    wordIds.forEach(function (wid) {
      var s = getWordState(wid);
      if (s.current_state === 'learned') learned++;
      else if (s.current_state === 'familiar') familiar++;
      else unseen++;
    });

    var total = wordIds.length;
    return {
      topic_id:       topicId,
      total:          total,
      learned:        learned,
      familiar:       familiar,
      unseen:         unseen,
      completion_pct: total ? Math.round(learned / total * 100) : 0
    };
  }

  /* ── OVERALL PROGRESS ──────────────────────────────────────────────────────── */
  function getOverallProgress() {
    // Derive learned/familiar from most recent check events per word
    var learnState  = {};   // word_id → true/false
    var famState    = {};   // word_id → true/false
    var trackedIds  = {};

    state.events.forEach(function (e) {
      var wid = e.word_id || (e.word ? resolveWordId(e.word) : null);
      if (!wid) return;
      trackedIds[wid] = true;
      if (e.event === 'word_checked') {
        if (e.checkbox_type === 'learned')   learnState[wid] = !!e.checked;
        if (e.checkbox_type === 'familiar')  famState[wid]   = !!e.checked;
      }
    });

    var learnedCount  = Object.keys(learnState).filter(function (k) { return learnState[k]; }).length;
    var familiarCount = Object.keys(famState).filter(function (k) {
      return famState[k] && !learnState[k];
    }).length;
    var trackedCount  = Object.keys(trackedIds).length;

    // Daily streak: consecutive days (UTC) with at least one session_start
    var sessionDates = state.events
      .filter(function (e) { return e.event === 'session_start'; })
      .map(function (e) { return new Date(e.timestamp).toISOString().slice(0, 10); });
    var uniqueDates = [];
    var seen = {};
    sessionDates.forEach(function (d) { if (!seen[d]) { seen[d] = true; uniqueDates.push(d); } });
    uniqueDates.sort().reverse();

    var streak = 0;
    var today  = new Date().toISOString().slice(0, 10);
    var check  = today;
    for (var i = 0; i < uniqueDates.length; i++) {
      if (uniqueDates[i] === check) {
        streak++;
        // decrement check by 1 day
        var d = new Date(check + 'T00:00:00Z');
        d.setUTCDate(d.getUTCDate() - 1);
        check = d.toISOString().slice(0, 10);
      } else {
        break;
      }
    }

    return {
      total_words:  TOTAL_WORDS,
      tracked:      trackedCount,
      learned:      learnedCount,
      familiar:     familiarCount,
      unseen:       TOTAL_WORDS - learnedCount - familiarCount,
      streak_days:  streak,
      sessions:     state.session_count || 0,
      total_events: state.events.length + pending.length
    };
  }

  /* ── FLOATING PANEL ────────────────────────────────────────────────────────── */
  function buildPanel() {
    var panel = document.createElement('div');
    panel.id = 'hsk-tracker-panel';
    panel.style.cssText = [
      'position:fixed', 'bottom:16px', 'right:16px', 'z-index:9999',
      'background:#1a1a2e', 'color:#e0e0e0', 'border-radius:10px',
      'padding:10px 14px', 'font-family:sans-serif', 'font-size:12px',
      'box-shadow:0 4px 18px rgba(0,0,0,0.4)', 'min-width:190px',
      'cursor:default', 'user-select:none', 'position:fixed'
    ].join(';');

    var title = document.createElement('div');
    title.style.cssText = 'font-weight:bold;margin-bottom:6px;color:#a29bfe;letter-spacing:.5px';
    title.textContent = '\uD83D\uDCCA Learning Tracker';

    var stats = document.createElement('div');
    stats.id = 'hsk-tracker-stats';
    stats.style.cssText = 'margin-bottom:8px;line-height:1.7;color:#ccc';

    var btnRow = document.createElement('div');
    btnRow.style.cssText = 'display:flex;gap:6px;flex-wrap:wrap';

    function makeBtn(label, color, fn) {
      var b = document.createElement('button');
      b.textContent = label;
      b.style.cssText = 'flex:1;padding:4px 6px;border:none;border-radius:5px;background:' +
        color + ';color:#fff;font-size:11px;cursor:pointer;font-weight:600';
      b.addEventListener('click', fn);
      return b;
    }

    btnRow.appendChild(makeBtn('\u2B07 Export', '#6c5ce7', function () { window.LearnerTracker.exportData(); }));
    btnRow.appendChild(makeBtn('\u2715 Clear',  '#d63031', function () { window.LearnerTracker.clear(); }));

    var toggle = document.createElement('div');
    toggle.style.cssText = 'position:absolute;top:8px;right:10px;cursor:pointer;color:#888;font-size:14px';
    toggle.textContent = '\u2212';
    var collapsed = false;
    toggle.addEventListener('click', function () {
      collapsed = !collapsed;
      stats.style.display  = collapsed ? 'none' : '';
      btnRow.style.display = collapsed ? 'none' : '';
      toggle.textContent = collapsed ? '+' : '\u2212';
    });

    panel.appendChild(toggle);
    panel.appendChild(title);
    panel.appendChild(stats);
    panel.appendChild(btnRow);
    document.body.appendChild(panel);

    refreshStats(stats);
    setInterval(function () { refreshStats(stats); }, 5000);
  }

  function refreshStats(el) {
    var p = getOverallProgress();
    el.innerHTML =
      '\uD83D\uDCDA <b>' + p.learned   + '</b> learned &nbsp;'
      + '\uD83D\uDC41 <b>' + p.familiar + '</b> familiar<br>'
      + '\uD83D\uDDD3 Streak: <b>' + p.streak_days + '</b>d &nbsp;'
      + 'Sessions: <b>' + p.sessions + '</b><br>'
      + '\uD83D\uDCDD Events: <b>' + p.total_events + '</b>';
  }

  /* ── EXPORT DATA ───────────────────────────────────────────────────────────── */
  function exportData() {
    flush();
    var progress = getOverallProgress();
    var payload = {
      learner_id:    state.learner_id,
      export_date:   new Date().toISOString().slice(0, 10),
      session_count: state.session_count,
      summary:       progress,
      events:        state.events
    };
    var blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    var url  = URL.createObjectURL(blob);
    var a    = document.createElement('a');
    a.href     = url;
    a.download = 'hsk_events_' + new Date().toISOString().slice(0, 10) + '.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /* ── CLEAR ─────────────────────────────────────────────────────────────────── */
  function clearData() {
    if (!confirm('Delete all tracking data? This cannot be undone.')) return;
    state   = blankState();
    pending = [];
    localStorage.removeItem(STORAGE_KEY);
    var statsEl = document.getElementById('hsk-tracker-stats');
    if (statsEl) { var p = getOverallProgress(); refreshStats(statsEl); }
    console.log('LearnerTracker: cleared.');
  }

  /* ── PUBLIC API ────────────────────────────────────────────────────────────── */
  window.LearnerTracker = {
    // Core
    track:    track,
    logEvent: function (wordId, eventType) {
      track({ event: eventType, word_id: wordId });
    },
    flush:    flush,

    // Progress queries
    getWordState:      getWordState,
    getTopicProgress:  getTopicProgress,
    getOverallProgress: getOverallProgress,
    getStats:          getOverallProgress,   // alias

    // Data management
    exportData: exportData,
    clear:      clearData,

    // Utility
    resolveWordId: resolveWordId
  };

  // Backward-compat alias for any code that still uses HSKTracker
  window.HSKTracker = window.LearnerTracker;

  /* -- LOAD TRACKER DATA -------------------------------------------------------- */
  function loadTrackerData() {
    fetch("data/tracker-data.json")
      .then(function(r) { return r.json(); })
      .then(function(d) {
        if (d.word_id_map)  WORD_ID_MAP  = d.word_id_map;
        if (d.topic_words)  TOPIC_WORDS  = d.topic_words;
        if (d.total_words)  TOTAL_WORDS  = d.total_words;
      })
      .catch(function() {
        /* data file unavailable -- tracker still works, word IDs will not resolve */
      });
  }

  /* -- INIT --------------------------------------------------------------------- */
  loadTrackerData();
  if (document.readyState === "loading") {
    window.onHskWordsReady(buildPanel);
  } else {
    buildPanel();
  }

})();
