"""
Run after every edit to words.xlsx:
    python prod/xlsx_to_json.py

Reads  : data/words.xlsx  (the editable master)
Writes : data/words.json      (machine-readable, for inspection / future tools)
         data/words-data.js   (browser-ready: window.HSK_WORDS = [...])

groups.json / groups-data.js are NOT touched here — they are generated by
migrate.py and describe structural metadata that does not change when you
edit word content.
"""
import json
from pathlib import Path
import openpyxl

ROOT      = Path(__file__).parent.parent
XLSX      = ROOT / "data" / "words.xlsx"
WORDS_J   = ROOT / "data" / "words.json"
WORDS_JS  = ROOT / "data" / "words-data.js"


def main():
    print(f"Reading {XLSX} ...")
    wb = openpyxl.load_workbook(XLSX, data_only=True, read_only=True)
    ws = wb["Words"]

    rows    = iter(ws.rows)
    headers = [cell.value for cell in next(rows)]
    words   = []

    for row in rows:
        obj = {}
        for col, cell in zip(headers, row):
            val = cell.value
            if val is None:
                val = 0 if col in ("id", "hsk") else ""
            obj[col] = val
        # Coerce types
        try:
            obj["hsk"] = int(obj["hsk"]) if obj["hsk"] else 0
        except (TypeError, ValueError):
            obj["hsk"] = 0
        try:
            obj["id"] = int(obj["id"]) if obj["id"] else 0
        except (TypeError, ValueError):
            pass
        # Stringify everything else that might be numeric by accident
        for k in ("word", "pinyin", "en", "ru",
                  "example_zh", "example_pinyin", "example_en", "example_ru",
                  "pos", "phonetic_group", "component"):
            obj[k] = str(obj[k]) if obj[k] is not None else ""

        words.append(obj)

    wb.close()

    # ── words.json ──────────────────────────────────────────────────────────
    WORDS_J.write_text(
        json.dumps(words, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"Wrote {WORDS_J}  ({len(words)} words)")

    # ── words-data.js ───────────────────────────────────────────────────────
    WORDS_JS.write_text(
        "window.HSK_WORDS=" + json.dumps(words, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {WORDS_JS}")


if __name__ == "__main__":
    main()
